[env:esp32dev]
platform = espressif32@6.5.0
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 115200

build_flags =
    -Isrc

lib_deps =
    adafruit/Adafruit MPU6050
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit BusIO
    IRremote